account/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index')
]

app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include(('home.urls', 'home'), namespace='home')),
    path('home/', include(('home.urls', 'home'), namespace='home')),
    path('admin/', admin.site.urls),
    path('my-account/', include(('account.urls', 'my-account'), namespace='my-account')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login_account/', views.login_account, name='login_account'),
    path('logout_account/', views.logout_account, name='logout_account')
]

account/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models
from django.core.validators import MinValueValidator


class UserDetails(models.Model):
    ud_id = models.AutoField(primary_key=True)
    ud_user_id = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE
    )
    ud_gender = models.CharField(blank=False, max_length=200)
    ud_birth_date = models.DateField(blank=False, null=True)
    ud_address = models.CharField(blank=True, max_length=200)
    ud_phone_number = models.CharField(blank=False, max_length=200)
    ud_profile_picture = models.CharField(blank=True, max_length=200)


class Event(models.Model):
    readonly_fields = ["event_organizer_user_id"];

    event_id = models.AutoField(primary_key=True)
    event_name = models.CharField(blank=False, max_length=200)
    event_start_datetime = models.DateTimeField(blank=False)
    event_end_datetime = models.DateTimeField(blank=False)
    event_description = models.TextField(blank=True)
    event_image = models.CharField(blank=False, max_length=200)
    event_max_users = models.IntegerField(blank=False, validators=[MinValueValidator(1)])
    event_organizer_user_id = models.ForeignKey(
        'auth.User',
        on_delete=models.DO_NOTHING
    )

    class Visibility(models.IntegerChoices):
        PUBLIC = 1
        PRIVATE = 2

    event_visibility = models.IntegerField(choices=Visibility.choices, default=Visibility.PUBLIC)


class EventAssignedUsers(models.Model):
    eau_id = models.AutoField(primary_key=True)
    eau_user_id = models.ForeignKey(
        'auth.User',
        on_delete=models.DO_NOTHING
    )
    eau_event_id = models.ForeignKey(
        Event,
        on_delete=models.DO_NOTHING
    )

    class Status(models.IntegerChoices):
        PENDING = 1
        ACCEPTED = 2
        DECLINED = 3

    eau_status = models.IntegerField(blank=False, choices=Status.choices, default=Status.PENDING)

home/models.py
from django.db import models

# Create your models here.

account/views.py
from django.http import HttpResponse
from django.template import loader


def index(request):
    template = loader.get_template('my-account/index.html')
    return HttpResponse(template.render({}, request))

home/views.py
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import HttpResponseRedirect
from django.http import JsonResponse

def index(request):
    template = loader.get_template('home/index.html')
    return HttpResponse(template.render({}, request))


def login_account(request):
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return JsonResponse({
                'success': True,
                'data': {
                    'url': 'my-account/'
                }
            })
        else:
            return JsonResponse({
                'success': False,
                'message': 'Invalid username or password!'
            })


def logout_account(request):
    logout(request)
    return HttpResponseRedirect('/')

account/templates/my-account/events_list.html
<table class="table_1 table table-striped table-bordered table-responsive" style="width:100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Datetime</th>
            <th>Description</th>
            <th>Current Users</th>
            <th>Max Users</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Event 1</td>
            <td>11-11-2020 14:00 - 16:00</td>
            <td>Example description</td>
            <td>0</td>
            <td>5</td>
        </tr>
        <tr>
            <td>Event 2</td>
            <td>11-12-2020 14:00 - 16:00</td>
            <td>Example description 2</td>
            <td>3</td>
            <td>6</td>
        </tr>
    </tbody>
</table>

account/templates/my-account/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Event Aggregation Service</title>
  {% load static %}
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/business-frontpage.css' %}" rel="stylesheet">

   <!-- Datatables core CSS -->
  <link href="{% static 'css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home:index' %}">Event Aggregation Service</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">My Account
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:logout_account' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
   </nav>
    <!-- Page Content -->
  <div class="container">
     <div class="row py-3">
      <div class="col-md-12 mb-5">
          <h3 class="py-2"> Upcoming Events </h3>
          {% include "my-account/events_list.html" %}
      </div>

    </div>
    <div class="row py-3">
      <div class="col-md-12 mb-5">
          <h3 class="py-2"> Past Events </h3>
          {% include "my-account/events_list.html" %}
      </div>
    </div>
  </div>
  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Event Aggregation Service 2020</p>
    </div>
    <!-- /.container -->
  </footer>

    <!-- Bootstrap core JavaScript -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/datatables.min.js' %}"></script>
  <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>
  <script>
      $(document).ready( function () {
            $('.table_1').DataTable();
      });
  </script>
</body>
</html>

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Event Aggregation Service</title>
  {% load static %}
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/business-frontpage.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Event Aggregation Service</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            {% if not request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
              </li>
            {% else %}
               <li class="nav-item">
                <a class="nav-link" href="{% url 'my-account:index' %}">My Account</a>
              </li>
            {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="#what-we-do">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#contact-us">Contact</a>
          </li>
            {% if not request.user.is_authenticated %}
              <li class="nav-item"  data-toggle="modal" data-target="#login-modal">
                <a class="nav-link" href="#">Login</a>
              </li>
            {% else %}
              <li class="nav-item" >
                <a class="nav-link" href="{% url 'home:logout_account' %}">Logout</a>
              </li>
            {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Event Aggregation Service</h1>
          <p class="lead mb-5 text-white-50">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non possimus ab labore provident mollitia. Id assumenda voluptate earum corporis facere quibusdam quisquam iste ipsa cumque unde nisi, totam quas ipsam.</p>
        </div>
      </div>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">

    <div class="row">
      <div class="col-md-8 mb-5">
        <h2 id="what-we-do">What We Do</h2>
        <hr>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A deserunt neque tempore recusandae animi soluta quasi? Asperiores rem dolore eaque vel, porro, soluta unde debitis aliquam laboriosam. Repellat explicabo, maiores!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis optio neque consectetur consequatur magni in nisi, natus beatae quidem quam odit commodi ducimus totam eum, alias, adipisci nesciunt voluptate. Voluptatum.</p>
        <a class="btn btn-primary btn-lg" href="#">Call to Action &raquo;</a>
      </div>
      <div class="col-md-4 mb-5">
        <h2 id="contact-us">Contact Us</h2>
        <hr>
        <address>
          <strong>Event Aggregation Service</strong>
          <br>3481 Melrose Place
          <br>Beverly Hills, CA 90210
          <br>
        </address>
        <address>
          <abbr title="Phone">P:</abbr>
          (123) 456-7890
          <br>
          <abbr title="Email">E:</abbr>
          <a href="mailto:#">name@example.com</a>
        </address>
      </div>
    </div>
    <!-- /.row -->

    <div class="row">
      <div class="col-md-8">
      <h2>Upcoming Events</h2>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="https://placehold.it/300x200" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#login-modal">Find Out More!</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="https://placehold.it/300x200" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#login-modal">Find Out More!</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="https://placehold.it/300x200" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#login-modal">Find Out More!</a>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Event Aggregation Service 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- The Modal -->
  <div class="modal fade login-register-modal" id="login-modal" tabindex="-1" role="dialog">
     <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header border-bottom-0">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-title text-center">
            <h4>Login</h4>
          </div>
          <div class="d-flex flex-column text-center">
            <form>
              <div class="form-group">
                <input name="username" type="email" class="form-control" class="email1"placeholder="Your email address...">
              </div>
              <div class="form-group">
                <input name="password" type="password" class="form-control" class="password1" placeholder="Your password...">
              </div>
              <button type="button" class="btn btn-primary btn-block btn-round btn-login">Login</button>
            </form>
          </div>
        </div>

        <div class="modal-footer d-flex justify-content-center">
          <div class="signup-section">Not a member yet? <a  href="#register-modal" data-toggle="modal" data-dismiss="modal"> Sign Up</a>.</div>
        </div>
    </div>
  </div>
  </div>
    <!-- The Modal -->
  <div class="modal fade login-register-modal" id="register-modal" tabindex="-1" role="dialog">
     <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header border-bottom-0">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-title text-center">
            <h4>Register</h4>
          </div>
          <div class="d-flex flex-column text-center">
            <form>
              <div class="form-group">
                <input type="email" class="form-control" class="email1"placeholder="Your email address...">
              </div>
              <div class="form-group">
                <input type="password" class="form-control" class="password1" placeholder="Your password...">
              </div>
              <div class="form-group">
                <input type="password" class="form-control" class="password2" placeholder="Repeat password...">
              </div>
              <button type="button" class="btn btn-primary btn-block btn-round">Register</button>
            </form>
          </div>
        </div>
    </div>
  </div>

 </div>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script>

  $(function () {
    $.ajaxSetup({
        headers: { "X-CSRFToken": getCookie("csrftoken") }
    });
});

  $(document.body).on('click', '#login-modal .btn-login', function(){
      $.ajax({
          type:"POST",
          url: '{% url 'home:login_account' %}',
          data: $('#login-modal form').serialize(),
          success: function(response){
              if (!response.success) {
                  alert(response.message);
              } else {
                  window.location.href = response.data.url;
              }
           }
      });
  });

  function getCookie(cname) {
      var name = cname + "=";
      var decodedCookie = decodeURIComponent(document.cookie);
      var ca = decodedCookie.split(';');
      for(var i = 0; i <ca.length; i++) {
          var c = ca[i];
          while (c.charAt(0) == ' ') {
             c = c.substring(1);
          }
          if (c.indexOf(name) == 0) {
             return c.substring(name.length, c.length);
          }
      }
      return "";
  }


</script>
</body>

</html>